name: Java CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start Database
      working-directory: ./aquario
      run: docker-compose up aquario_db

    - name: Build Docker image
      working-directory: ./aquario
      run: docker build . --file Dockerfile --tag aquario-api:latest

    - name: Run Docker Compose
      working-directory: ./aquario
      run: docker-compose up -d
